Added functionality to combine 2 MODS fields when present in solr metadata display
discoverygarden/chs_theme pull request #9
Opened 2017-05-05 12:57 UTC by BrandonMorr

2017-05-09 11:37 UTC, jordandukart requested changes

2017-05-09 11:37 UTC, jordandukart commented on template.php
> +  if (isset($solr_fields['mods_accessCondition_useAndReproduction_xlinkhref_ms']) && isset($solr_fields['mods_accessCondition_useAndReproduction_ms'])) {
I wouldn't expose having the `mods_accessCondition_useAndReproduction_xlinkhref_ms` field being present in the metadata display as it clogs up the UI when it doesn't have to. Seeing as you are grabbing the value and unsetting it later you could add it to `$variables['solr_fields']` array in https://github.com/discoverygarden/chs_theme/blob/7.x/template.php#L128-Lundefined and unsetting it here again after using it.

2017-05-09 11:37 UTC, jordandukart commented on template.php
> +      $variables['solr_fields']['mods_accessCondition_useAndReproduction_ms']['value'] = array(
This straight up stomps on any and all modification to the values that were here previously as at this point the markup is rendered. For example if you were to put truncation on this field this completely stomps it away. Hyperlinking and truncation completely cannot work in Solr metadata though so maybe this is a moot point? This still needs to be communicated to the client. Similarly if this field had multiple values (it is a ms field after all) you squashed all the values.

2017-05-09 11:37 UTC, jordandukart commented on template.php
> +    $anchor = "<a href='$link'>$value</a>";
Any particular reason you aren't using [l](https://api.drupal.org/api/drupal/includes%21common.inc/function/l/7.x)?

2017-05-11 13:33 UTC, BrandonMorr commented
Updated pull, client confirmed that this code will suit their use case.

2017-05-11 15:03 UTC, merged